KEY(classes_root               , HKEY_CLASSES_ROOT               , HKCR  )
KEY(current_user               , HKEY_CURRENT_USER               , HKCU  )
KEY(local_machine              , HKEY_LOCAL_MACHINE              , HKLM  )
KEY(users                      , HKEY_USERS                      , HKU   )
KEY(performance_data           , HKEY_PERFORMANCE_DATA           , HKPD  )
KEY(performance_text           , HKEY_PERFORMANCE_TEXT           , HKPT  )
KEY(performance_nlstext        , HKEY_PERFORMANCE_NLSTEXT        , HKPN  )
KEY(current_config             , HKEY_CURRENT_CONFIG             , HKCC  )
KEY(dyn_data                   , HKEY_DYN_DATA                   , HKDD  )
KEY(current_user_local_settings, HKEY_CURRENT_USER_LOCAL_SETTINGS, HKCULS)

#undef KEY
